from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    title: str
    url: str
    retrieved: str
    jurisdiction: str
    category: str


@dataclass(frozen=True)
class KnowledgeItem:
    key: str
    title: str
    text: str
    source: Source
    tags: tuple[str, ...]
    risk: str = "normal"


RETRIEVED_DATE = "2026-06-13"


SOURCES = {
    "healthdirect_snake": Source(
        "Healthdirect - Snake bites",
        "https://www.healthdirect.gov.au/snake-bites",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_spider": Source(
        "Healthdirect - Spider bites",
        "https://www.healthdirect.gov.au/spider-bites",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_poisoning": Source(
        "Healthdirect - toxin exposure",
        "https://www.healthdirect.gov.au/poisoning",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_stinging_plants": Source(
        "Healthdirect - Stinging plants",
        "https://www.healthdirect.gov.au/stinging-plants",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "nsw_mushrooms": Source(
        "NSW Health - wild mushroom safety",
        "https://www.health.nsw.gov.au/environment/factsheets/Pages/wild-mushroom-poisoning.aspx",
        RETRIEVED_DATE,
        "NSW / Australia",
        "fungi",
    ),
    "nsw_bushwalking": Source(
        "NSW National Parks - Bushwalking safety",
        "https://www.nationalparks.nsw.gov.au/safety/bushwalking-safety",
        RETRIEVED_DATE,
        "NSW / Australia",
        "preparedness",
    ),
    "emergency_plus": Source(
        "Emergency+",
        "https://www.emergencyplus.com.au/",
        RETRIEVED_DATE,
        "Australia",
        "emergency",
    ),
    "bom_climate_data": Source(
        "Bureau of Meteorology - Climate Data Online",
        "https://www.bom.gov.au/climate/data/",
        RETRIEVED_DATE,
        "Australia",
        "weather",
    ),
    "bom_climate_maps": Source(
        "Bureau of Meteorology - Climate classification maps",
        "https://www.bom.gov.au/climate/maps/averages/climate-classification/",
        RETRIEVED_DATE,
        "Australia",
        "weather",
    ),
    "australian_museum_dangerous": Source(
        "Australian Museum - Dangerous animals",
        "https://australian.museum/learn/animals/dangerous-animals/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "wiki_australia": Source(
        "Wikipedia compressed pack - Australia",
        "https://en.wikipedia.org/wiki/Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_climate": Source(
        "Wikipedia compressed pack - Climate of Australia",
        "https://en.wikipedia.org/wiki/Climate_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_flora": Source(
        "Wikipedia compressed pack - Flora of Australia",
        "https://en.wikipedia.org/wiki/Flora_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_fauna": Source(
        "Wikipedia compressed pack - Fauna of Australia",
        "https://en.wikipedia.org/wiki/Fauna_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_regions": Source(
        "Wikipedia compressed pack - Australian regions",
        "https://en.wikipedia.org/wiki/IBRA",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
}


KNOWLEDGE_ITEMS: tuple[KnowledgeItem, ...] = (
    KnowledgeItem(
        "snake_bite",
        "Snake bite emergency flow",
        "Treat any suspected snake bite as serious. Call Triple Zero (000). Keep the person still, apply a pressure immobilisation bandage if trained and available, immobilise the limb, and do not wash, cut, suck, or tourniquet the bite. The goal is to slow venom movement and get medical help.",
        SOURCES["healthdirect_snake"],
        ("snake", "bite", "pressure immobilisation", "venom", "first aid"),
        "critical",
    ),
    KnowledgeItem(
        "spider_bite",
        "Spider bite emergency flow",
        "For funnel-web or mouse spider bite, call Triple Zero (000), keep the person still, and use pressure immobilisation. For many other spider bites, clean the area, use a cold pack, and seek medical help if severe symptoms occur. If unsure, choose the more cautious pathway.",
        SOURCES["healthdirect_spider"],
        ("spider", "funnel-web", "mouse spider", "redback", "bite", "first aid"),
        "high",
    ),
    KnowledgeItem(
        "poisoning",
        "Toxin exposure escalation",
        "If someone may have swallowed, inhaled, or touched a toxin, call 13 11 26 for advice. If they are unconscious, not breathing, fitting, collapsing, or severely unwell, call Triple Zero (000) immediately.",
        SOURCES["healthdirect_poisoning"],
        ("poison", "poisoning", "toxin", "ingested", "ate", "13 11 26"),
        "critical",
    ),
    KnowledgeItem(
        "mushrooms",
        "Wild mushroom rule",
        "Do not eat wild mushrooms. Dangerous and deadly mushrooms can look similar to edible species, and photo identification is not safe enough for consumption decisions. If someone has eaten a wild mushroom, call 13 11 26 or Triple Zero (000) if they are seriously unwell.",
        SOURCES["nsw_mushrooms"],
        ("mushroom", "fungus", "fungi", "death cap", "forage", "eat", "bush tucker"),
        "critical",
    ),
    KnowledgeItem(
        "stinging_plants",
        "Stinging plants",
        "Avoid contact with stinging trees and unknown hairy or irritating plants. If stung by a stinging tree, do not rub the area. Healthdirect notes there is no agreed first aid treatment; wax strips may help remove fine hairs. Seek medical care for severe pain or systemic symptoms.",
        SOURCES["healthdirect_stinging_plants"],
        ("stinging tree", "gympie", "plant", "leaf", "hair", "sting"),
        "high",
    ),
    KnowledgeItem(
        "bushwalking_safety",
        "Bushwalking preparation",
        "Before a walk, check conditions, carry water, food, first aid, navigation, warm and wet-weather layers, and tell someone your route and return time. Consider a personal locator beacon for remote areas.",
        SOURCES["nsw_bushwalking"],
        ("checklist", "prepare", "route", "water", "gear", "plb", "beacon"),
        "normal",
    ),
    KnowledgeItem(
        "emergency_orientation",
        "Emergency orientation",
        "If lost or injured, stop, stay calm, conserve battery, stay visible, shelter from exposure, and use exact location information when contacting help. Emergency+ helps communicate GPS coordinates to emergency services when a phone can connect.",
        SOURCES["emergency_plus"],
        ("lost", "navigation", "gps", "000", "112", "emergency", "location"),
        "high",
    ),
    KnowledgeItem(
        "climate_averages",
        "Climate averages, not live forecasts",
        "BoM climate data and climate classification maps are useful for broad seasonal expectations, but they do not replace checking live forecasts, fire danger, flood risk, and park closures before departure.",
        SOURCES["bom_climate_data"],
        ("weather", "climate", "forecast", "temperature", "rain", "bom"),
        "normal",
    ),
    KnowledgeItem(
        "climate_regions",
        "Australian climate regions",
        "Northern tropical areas can bring heat, humidity, monsoon rain, and cyclone-season risks. Southern alpine and tableland areas can change quickly and bring cold exposure. Arid interiors can swing between extreme heat and cold nights. Coastal and temperate areas can still change rapidly.",
        SOURCES["bom_climate_maps"],
        ("tropical", "arid", "alpine", "coastal", "temperate", "desert"),
        "normal",
    ),
    KnowledgeItem(
        "dangerous_animals",
        "Dangerous animals",
        "Australia has venomous snakes and spiders plus other dangerous animals. Do not handle unknown wildlife. Back away calmly, give animals space, and treat bites or severe stings as potentially serious.",
        SOURCES["australian_museum_dangerous"],
        ("dangerous", "animal", "snake", "spider", "wildlife", "venomous"),
        "high",
    ),
    KnowledgeItem(
        "bleeding",
        "Severe bleeding",
        "For severe bleeding, apply firm direct pressure with a clean pad or clothing, keep pressure on, call Triple Zero (000) for major bleeding, and monitor for shock. Do not remove embedded objects; pad around them.",
        SOURCES["healthdirect_poisoning"],
        ("bleeding", "blood", "wound", "cut", "shock"),
        "critical",
    ),
    KnowledgeItem(
        "heat_illness",
        "Heat illness",
        "Heat stress can escalate quickly. Move to shade, rest, cool the person, sip water if conscious, and seek urgent help for confusion, collapse, seizures, hot dry skin, or worsening symptoms.",
        SOURCES["nsw_bushwalking"],
        ("heat", "dehydration", "sun", "hot", "thirst", "heatstroke"),
        "high",
    ),
    KnowledgeItem(
        "hypothermia",
        "Cold exposure",
        "Cold, wind, wet clothing, and fatigue can cause hypothermia even outside alpine areas. Add dry insulation, shelter from wind and rain, share warmth, avoid further heat loss, and seek help for confusion, drowsiness, or severe shivering.",
        SOURCES["nsw_bushwalking"],
        ("cold", "hypothermia", "exposure", "rain", "wind", "shivering"),
        "high",
    ),
    KnowledgeItem(
        "australian_bushland",
        "Australian bushland",
        "Bushland covers many Australian plant communities, from eucalypt woodland and heath to dry sclerophyll forest. For walkers, the practical pattern is shade can be sparse, water can be unreliable, and tracks can look similar after fire, flood, or regrowth.",
        SOURCES["wiki_australia"],
        ("australia", "bushland", "bush", "woodland", "sclerophyll", "track"),
        "normal",
    ),
    KnowledgeItem(
        "eucalypt_forest",
        "Eucalypt forest",
        "Eucalypt forests dominate many walking areas. Bark ribbons, oil-rich leaves, fallen limbs, and open understory are common. In heat, wind, or after storms, be mindful of falling branches, dry fuel, and limited shade on ridges.",
        SOURCES["wiki_flora"],
        ("eucalyptus", "eucalypt", "gum tree", "forest", "woodland", "bark"),
        "normal",
    ),
    KnowledgeItem(
        "acacia_wattle",
        "Acacia and wattle",
        "Acacias, often called wattles, are widespread in Australia. Many have yellow flower heads or spikes and flattened leaf-like phyllodes. Some species have irritant sap or sharp growth, so use observation rather than handling.",
        SOURCES["wiki_flora"],
        ("acacia", "wattle", "yellow flower", "phyllode", "shrub"),
        "normal",
    ),
    KnowledgeItem(
        "banksia",
        "Banksia",
        "Banksias are Australian shrubs and trees with distinctive flower spikes and woody cones. They are useful habitat markers for birds and insects, and often occur in sandy coastal heath, woodland, and dry forest.",
        SOURCES["wiki_flora"],
        ("banksia", "flower spike", "cone", "heath", "coastal", "woodland"),
        "normal",
    ),
    KnowledgeItem(
        "grass_tree",
        "Grass tree",
        "Grass trees have long narrow leaves, a dark trunk or skirt, and tall flower spikes. They grow slowly and can be damaged by trampling; stay on track and avoid breaking flower spikes or leaves.",
        SOURCES["wiki_flora"],
        ("grass tree", "xanthorrhoea", "flower spike", "dry forest", "heath"),
        "normal",
    ),
    KnowledgeItem(
        "spinifex",
        "Spinifex grasslands",
        "Spinifex forms tough hummock grass across arid and semi-arid Australia. It can be sharp, slow to cross, and associated with exposed heat, low water availability, and long distances between shade.",
        SOURCES["wiki_flora"],
        ("spinifex", "hummock grass", "arid", "desert", "exposure"),
        "normal",
    ),
    KnowledgeItem(
        "mangroves",
        "Mangroves",
        "Mangroves grow in tidal coastal zones and estuaries. Walkers should plan around tides, mud, heat, insects, and crocodile country in the north. Boardwalks and marked routes are safer than crossing mudflats.",
        SOURCES["wiki_flora"],
        ("mangrove", "estuary", "tide", "mudflat", "coastal", "crocodile"),
        "high",
    ),
    KnowledgeItem(
        "rainforest",
        "Australian rainforest",
        "Australian rainforests range from tropical north Queensland to temperate gullies in the south. They can bring slippery roots, leeches, low visibility, fast creek rises, and stinging plants near track edges.",
        SOURCES["wiki_regions"],
        ("rainforest", "tropical", "temperate", "leech", "creek", "stinging plant"),
        "normal",
    ),
    KnowledgeItem(
        "alpine_australia",
        "Australian alpine country",
        "Australian alpine and subalpine areas can shift from mild to cold, wet, windy, or whiteout-like conditions quickly. Carry insulation, rain gear, navigation, and a conservative turnaround plan.",
        SOURCES["wiki_regions"],
        ("alpine", "snowy mountains", "high country", "kosciuszko", "cold", "whiteout"),
        "high",
    ),
    KnowledgeItem(
        "blue_mountains",
        "Blue Mountains bushwalking",
        "The Blue Mountains combine sandstone cliffs, eucalyptus forest, steep stairs, waterfalls, and creek gullies. Plan for rapid weather shifts, exposed lookouts, slippery tracks after rain, and cold or windy conditions on ridges.",
        SOURCES["wiki_regions"],
        ("blue mountains", "katoomba", "sandstone", "cliff", "lookout", "waterfall", "bushwalking"),
        "normal",
    ),
    KnowledgeItem(
        "arid_interior",
        "Arid interior",
        "The arid interior has high exposure, long distances, limited water, and large day-night temperature swings. Walkers should plan water, shade, vehicle recovery, satellite communication, and conservative timing around heat.",
        SOURCES["wiki_regions"],
        ("arid", "interior", "desert", "red centre", "water", "heat"),
        "high",
    ),
    KnowledgeItem(
        "tropical_north",
        "Tropical north",
        "Northern Australia has a strong wet-dry seasonal rhythm. Wet-season travel can involve intense rain, flooded crossings, lightning, heat stress, and access closures; dry-season travel still needs heat and water planning.",
        SOURCES["wiki_climate"],
        ("tropical", "north", "wet season", "dry season", "monsoon", "flood"),
        "high",
    ),
    KnowledgeItem(
        "temperate_south",
        "Temperate southern Australia",
        "Southern temperate regions can bring cool changes, fronts, wind, rain, and rapid shifts between sun and cold exposure. Layering, rain protection, and a head torch matter even on short walks.",
        SOURCES["wiki_climate"],
        ("temperate", "southern", "front", "rain", "wind", "cool change"),
        "normal",
    ),
    KnowledgeItem(
        "east_coast_lows",
        "East coast lows",
        "East coast lows can bring damaging wind, heavy rain, rough seas, and fast-changing coastal or range conditions. For bushwalkers this means creek crossings, cliffs, beaches, and exposed ridges deserve extra caution.",
        SOURCES["wiki_climate"],
        ("east coast low", "coast", "heavy rain", "wind", "creek", "ridge"),
        "high",
    ),
    KnowledgeItem(
        "southerly_buster",
        "Southerly buster",
        "A southerly buster is a strong cool southerly change that can affect parts of southeast Australia, especially coastal New South Wales. It may bring abrupt wind, temperature drop, and rough coastal conditions.",
        SOURCES["wiki_climate"],
        ("southerly buster", "cool change", "wind", "coast", "nsw"),
        "normal",
    ),
    KnowledgeItem(
        "cumulonimbus",
        "Cumulonimbus cloud",
        "Tall cauliflower-like cloud with dark bases or an anvil top can indicate thunderstorm development. Treat cloud reading as an observation, not a forecast, and avoid exposed ridges, lone trees, and creek beds as storms build.",
        SOURCES["wiki_climate"],
        ("cloud", "cumulonimbus", "anvil", "storm", "lightning", "weather"),
        "high",
    ),
    KnowledgeItem(
        "kangaroo_wallaby",
        "Kangaroos and wallabies",
        "Kangaroos and wallabies are common macropods. Give them space, especially large males and animals near roads or campsites. Avoid feeding wildlife, which can make animals bolder and less healthy.",
        SOURCES["wiki_fauna"],
        ("kangaroo", "wallaby", "macropod", "wildlife", "camp"),
        "normal",
    ),
    KnowledgeItem(
        "wombat",
        "Wombat",
        "Wombats are sturdy burrowing marsupials. Burrows can undermine ground near tracks and camps. Give animals space, avoid blocking burrow entrances, and watch footing around holes in low light.",
        SOURCES["wiki_fauna"],
        ("wombat", "burrow", "marsupial", "track", "hole"),
        "normal",
    ),
    KnowledgeItem(
        "koala",
        "Koala",
        "Koalas live in eucalypt habitats and may be high in trees or moving on the ground between trees. Keep distance, keep dogs away, and report injured animals to local wildlife rescue where possible.",
        SOURCES["wiki_fauna"],
        ("koala", "eucalypt", "wildlife", "rescue", "tree"),
        "normal",
    ),
    KnowledgeItem(
        "echidna",
        "Echidna",
        "Echidnas are monotremes with spines and a long snout. If encountered, give space and avoid disturbing them; they may dig in or curl up when stressed.",
        SOURCES["wiki_fauna"],
        ("echidna", "monotreme", "spines", "snout", "wildlife"),
        "normal",
    ),
    KnowledgeItem(
        "platypus",
        "Platypus",
        "Platypus live around freshwater creeks and rivers. Sightings are easiest at quiet dawn or dusk. Do not disturb banks or burrows; males have venomous spurs, so never handle one.",
        SOURCES["wiki_fauna"],
        ("platypus", "creek", "river", "freshwater", "spur", "venom"),
        "normal",
    ),
    KnowledgeItem(
        "dingo",
        "Dingo",
        "Dingoes are wild canids found in many regions. Keep food secured, do not feed them, supervise children, and follow local park guidance. Back away calmly if one approaches.",
        SOURCES["wiki_fauna"],
        ("dingo", "wild dog", "canid", "camp", "food", "fraser island", "kgari"),
        "high",
    ),
    KnowledgeItem(
        "cassowary",
        "Cassowary",
        "Cassowaries inhabit parts of tropical north Queensland. They are large, powerful birds. Do not feed or approach them; give a clear escape path and back away calmly.",
        SOURCES["wiki_fauna"],
        ("cassowary", "tropical", "queensland", "bird", "rainforest"),
        "high",
    ),
    KnowledgeItem(
        "crocodile_country",
        "Crocodile country",
        "Saltwater crocodiles occur across northern Australia in coastal, river, wetland, and sometimes inland floodplain habitats. Stay back from water edges and follow local signs and ranger advice.",
        SOURCES["wiki_fauna"],
        ("crocodile", "saltwater crocodile", "north", "river", "wetland", "estuary"),
        "critical",
    ),
    KnowledgeItem(
        "ticks_leeches",
        "Ticks and leeches",
        "Ticks and leeches are common in some humid bushland and rainforest areas. Wear protective clothing, check skin after walks, remove ticks carefully, and monitor for allergic reactions or illness.",
        SOURCES["wiki_fauna"],
        ("tick", "leech", "rainforest", "bite", "allergy", "skin"),
        "normal",
    ),
    KnowledgeItem(
        "bull_ant",
        "Bull ants",
        "Bull ants are large Australian ants with painful stings and strong vision. Avoid nests and do not stand on mound areas. People with severe allergic reactions need urgent medical care.",
        SOURCES["wiki_fauna"],
        ("bull ant", "ant", "sting", "nest", "allergy"),
        "high",
    ),
    KnowledgeItem(
        "blue_bottle",
        "Bluebottle",
        "Bluebottles can wash onto Australian beaches and cause painful stings. Avoid touching stranded tentacles and check local beach advice before swimming or coastal walking.",
        SOURCES["wiki_fauna"],
        ("bluebottle", "beach", "sting", "tentacle", "coast"),
        "normal",
    ),
    KnowledgeItem(
        "box_jellyfish",
        "Box jellyfish",
        "Box jellyfish and Irukandji risk is concentrated in northern tropical waters, especially warmer months. Use stinger-resistant swimwear, obey local signs, and avoid swimming where stinger risk is posted.",
        SOURCES["wiki_fauna"],
        ("box jellyfish", "irukandji", "stinger", "tropical", "beach", "north"),
        "critical",
    ),
    KnowledgeItem(
        "blue_ringed_octopus",
        "Blue-ringed octopus",
        "Blue-ringed octopuses can occur in tide pools and shallow coastal waters. They are small and highly venomous. Do not handle shells, rocks, or marine animals from rock pools.",
        SOURCES["wiki_fauna"],
        ("blue-ringed octopus", "tide pool", "rock pool", "marine", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "stonefish",
        "Stonefish",
        "Stonefish are well-camouflaged venomous fish found in some northern coastal and reef environments. Wear protective footwear in suitable habitat and avoid placing hands or feet where you cannot see.",
        SOURCES["wiki_fauna"],
        ("stonefish", "reef", "coast", "venom", "footwear"),
        "critical",
    ),
    KnowledgeItem(
        "brown_snake",
        "Eastern brown snake",
        "Eastern brown snakes are widespread in eastern Australia and are medically important. Do not approach or attempt to identify closely. Stand still or back away slowly and leave an escape path.",
        SOURCES["wiki_fauna"],
        ("eastern brown snake", "brown snake", "snake", "venom", "grassland"),
        "critical",
    ),
    KnowledgeItem(
        "tiger_snake",
        "Tiger snake",
        "Tiger snakes occur in southern Australia and often around wetlands, creeks, or damp habitats. Keep distance from snakes and use the snake bite flow for any suspected bite.",
        SOURCES["wiki_fauna"],
        ("tiger snake", "snake", "wetland", "creek", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "taipan",
        "Taipan",
        "Taipans are highly venomous Australian snakes, including coastal and inland species. Most walkers should never try to distinguish species in the field; distance and first-aid response matter more.",
        SOURCES["wiki_fauna"],
        ("taipan", "snake", "coastal taipan", "inland taipan", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "redback_spider",
        "Redback spider",
        "Redback spiders are common around dry sheltered places, including toilets, sheds, gear, and campsites. Shake out gear, use gloves around stored items, and seek care for severe pain or systemic symptoms.",
        SOURCES["wiki_fauna"],
        ("redback", "spider", "camp", "toilet", "gear", "bite"),
        "high",
    ),
    KnowledgeItem(
        "funnel_web_spider",
        "Funnel-web spider",
        "Funnel-web spiders occur in parts of eastern Australia and can shelter in damp ground, burrows, shoes, or gear. Avoid handling spiders and use the pressure immobilisation pathway for suspected serious bites.",
        SOURCES["wiki_fauna"],
        ("funnel-web", "spider", "burrow", "shoe", "gear", "bite"),
        "critical",
    ),
    KnowledgeItem(
        "bush_tucker_context",
        "Bush tucker context",
        "Bush tucker knowledge is local, seasonal, and culturally grounded. Treat general app notes as education only. Do not consume wild foods without expert local identification and permission to harvest.",
        SOURCES["wiki_flora"],
        ("bush tucker", "foraging", "edible", "food", "indigenous knowledge", "seasonal"),
        "high",
    ),
    KnowledgeItem(
        "track_navigation",
        "Track navigation in Australian bush",
        "Australian tracks can become unclear after fire, flood, leaf fall, or animal pads. Use map, compass or GPS, turn back early when uncertain, and avoid splitting the group.",
        SOURCES["wiki_australia"],
        ("navigation", "track", "map", "gps", "lost", "bushwalking"),
        "normal",
    ),
    KnowledgeItem(
        "water_crossings",
        "Creek and river crossings",
        "Creeks can rise quickly after upstream rain, especially in gorges, tropics, and steep catchments. If a crossing looks fast, deep, cloudy, or rising, wait or turn back.",
        SOURCES["wiki_regions"],
        ("creek", "river", "crossing", "flood", "gorge", "rain"),
        "high",
    ),
    KnowledgeItem(
        "fire_weather_context",
        "Fire weather context",
        "Hot, dry, windy weather can make bushfire behaviour more dangerous. Offline notes cannot know current fire danger, so check official fire services before leaving service and avoid remote routes on severe days.",
        SOURCES["wiki_climate"],
        ("fire", "bushfire", "wind", "heat", "dry", "fire danger"),
        "high",
    ),
)


DANGER_CARDS = (
    {
        "title": "Snakes",
        "severity": "critical",
        "signals": "Any suspected bite, unexplained collapse, bite marks, or seeing a snake nearby.",
        "actions": [
            "Call Triple Zero (000).",
            "Keep the person still and calm.",
            "Use pressure immobilisation if trained and available.",
            "Do not wash, cut, suck, or tourniquet the bite.",
        ],
        "source": SOURCES["healthdirect_snake"],
    },
    {
        "title": "Funnel-web or mouse spider",
        "severity": "critical",
        "signals": "Large dark spider, severe pain, sweating, tingling, nausea, breathing trouble, or uncertainty.",
        "actions": [
            "Call Triple Zero (000).",
            "Keep still.",
            "Use pressure immobilisation for suspected funnel-web or mouse spider bite.",
        ],
        "source": SOURCES["healthdirect_spider"],
    },
    {
        "title": "Wild mushrooms",
        "severity": "critical",
        "signals": "Any wild mushroom or unknown fungus, even if it looks familiar.",
        "actions": [
            "Do not eat wild mushrooms.",
            "Do not rely on a photo to decide if a mushroom is edible.",
            "If eaten, call 13 11 26 or 000 if seriously unwell.",
        ],
        "source": SOURCES["nsw_mushrooms"],
    },
    {
        "title": "Stinging trees and irritating plants",
        "severity": "high",
        "signals": "Hairy leaves/stems, rainforest tracks, sudden intense sting, embedded fine hairs.",
        "actions": [
            "Do not rub the area.",
            "Avoid touching unknown hairy plants.",
            "Seek medical care for severe pain or systemic symptoms.",
        ],
        "source": SOURCES["healthdirect_stinging_plants"],
    },
    {
        "title": "Heat, dehydration, and exposure",
        "severity": "high",
        "signals": "Confusion, collapse, severe thirst, no sweating, shivering, drowsiness, worsening fatigue.",
        "actions": [
            "Stop and shelter from the hazard.",
            "Cool or warm the person as appropriate.",
            "Escalate early if symptoms are severe or worsening.",
        ],
        "source": SOURCES["nsw_bushwalking"],
    },
)


CHECKLIST_SECTIONS = (
    {
        "title": "Tell someone",
        "items": [
            "Route, party names, vehicle details, planned return time, and escalation time.",
            "Emergency contact understands when to raise the alarm.",
        ],
    },
    {
        "title": "Navigation and communication",
        "items": [
            "Offline map or paper map and compass.",
            "Phone charged, power bank packed, location services enabled.",
            "PLB or satellite communicator for remote routes.",
            "Emergency+ installed and tested before losing service.",
        ],
    },
    {
        "title": "Water, food, and weather",
        "items": [
            "Enough water plus backup treatment plan.",
            "Food plus emergency extra.",
            "Live BoM forecast, fire danger, park status, and flood/track conditions checked before departure.",
        ],
    },
    {
        "title": "First aid and exposure",
        "items": [
            "First aid kit with snake bandage, wound dressings, blister care, and any personal medicines.",
            "Sun protection, rain shell, warm layer, and head torch.",
            "Know the limits: Outbush AI is a field aid, not emergency services or medical care.",
        ],
    },
)
