from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    title: str
    url: str
    retrieved: str
    jurisdiction: str
    category: str


@dataclass(frozen=True)
class KnowledgeItem:
    key: str
    title: str
    text: str
    source: Source
    tags: tuple[str, ...]
    risk: str = "normal"


RETRIEVED_DATE = "2026-06-14"


SOURCES = {
    "healthdirect_snake": Source(
        "Healthdirect - Snake bites",
        "https://www.healthdirect.gov.au/snake-bites",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_spider": Source(
        "Healthdirect - Spider bites",
        "https://www.healthdirect.gov.au/spider-bites",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_poisoning": Source(
        "Healthdirect - toxin exposure",
        "https://www.healthdirect.gov.au/poisoning",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "healthdirect_stinging_plants": Source(
        "Healthdirect - Stinging plants",
        "https://www.healthdirect.gov.au/stinging-plants",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "nsw_mushrooms": Source(
        "NSW Health - wild mushroom safety",
        "https://www.health.nsw.gov.au/environment/factsheets/Pages/wild-mushroom-poisoning.aspx",
        RETRIEVED_DATE,
        "NSW / Australia",
        "fungi",
    ),
    "nsw_bushwalking": Source(
        "NSW National Parks - Bushwalking safety",
        "https://www.nationalparks.nsw.gov.au/safety/bushwalking-safety",
        RETRIEVED_DATE,
        "NSW / Australia",
        "preparedness",
    ),
    "nsw_trip_intentions": Source(
        "NSW National Parks - Trip intention form",
        "https://www.nationalparks.nsw.gov.au/safety/bushwalking-safety/think-before-you-trek/trip-intention-form",
        "2026-06-15",
        "NSW / Australia",
        "preparedness",
    ),
    "emergency_plus": Source(
        "Emergency+",
        "https://www.emergencyplus.com.au/",
        RETRIEVED_DATE,
        "Australia",
        "emergency",
    ),
    "bom_climate_data": Source(
        "Bureau of Meteorology - Climate Data Online",
        "https://www.bom.gov.au/climate/data/",
        RETRIEVED_DATE,
        "Australia",
        "weather",
    ),
    "bom_climate_maps": Source(
        "Bureau of Meteorology - Climate classification maps",
        "https://www.bom.gov.au/climate/maps/averages/climate-classification/",
        RETRIEVED_DATE,
        "Australia",
        "weather",
    ),
    "australian_museum_dangerous": Source(
        "Australian Museum - Dangerous animals",
        "https://australian.museum/learn/animals/dangerous-animals/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_yellow_bellied_sea_snake": Source(
        "Australian Museum - Yellow-bellied Sea Snake",
        "https://australian.museum/learn/animals/reptiles/yellow-bellied-sea-snake/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_red_bellied_black_snake": Source(
        "Australian Museum - Red-bellied Black Snake",
        "https://australian.museum/learn/animals/reptiles/red-bellied-black-snake/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_eastern_brown_snake": Source(
        "Australian Museum - Eastern Brown Snake",
        "https://australian.museum/learn/animals/reptiles/eastern-brown-snake/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_western_brown_snake": Source(
        "Australian Museum - Western Brown Snakes",
        "https://australian.museum/learn/animals/reptiles/western-brown-snakes/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_tiger_snake": Source(
        "Australian Museum - Tiger Snake",
        "https://australian.museum/learn/animals/reptiles/tiger-snake/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_coastal_taipan": Source(
        "Australian Museum - Coastal Taipan",
        "https://australian.museum/learn/animals/reptiles/coastal-taipan/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_inland_taipan": Source(
        "Australian Museum - Inland Taipan",
        "https://australian.museum/learn/animals/reptiles/inland-taipan/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_sydney_funnel_web": Source(
        "Australian Museum - Sydney Funnel-web Spider",
        "https://australian.museum/learn/animals/spiders/sydney-funnel-web-spider/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_redback_spider": Source(
        "Australian Museum - Redback Spider",
        "https://australian.museum/learn/animals/spiders/redback-spider/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "qld_poisons_spider": Source(
        "Queensland Poisons Information Centre - Spider bites",
        "https://www.poisonsinfo.health.qld.gov.au/bites-and-stings/spider-bites",
        RETRIEVED_DATE,
        "Queensland / Australia",
        "first_aid",
    ),
    "healthdirect_jellyfish": Source(
        "Healthdirect - Jellyfish stings",
        "https://www.healthdirect.gov.au/jellyfish-stings",
        RETRIEVED_DATE,
        "Australia",
        "first_aid",
    ),
    "qld_poisons_sea_creatures": Source(
        "Queensland Poisons Information Centre - Sea creature bites and stings",
        "https://www.poisonsinfo.health.qld.gov.au/bites-and-stings/sea-creature-bites-and-stings",
        RETRIEVED_DATE,
        "Queensland / Australia",
        "first_aid",
    ),
    "am_blue_ringed_octopus": Source(
        "Australian Museum - Blue-lined Octopus",
        "https://australian.museum/learn/animals/molluscs/blue-lined-octopus/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_stonefish": Source(
        "Australian Museum - Reef Stonefish",
        "https://australian.museum/learn/animals/fishes/reef-stonefish-synanceia-verrucosa-bloch-schneider-1801/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_box_jellyfish": Source(
        "Australian Museum - Box Jellyfish",
        "https://australian.museum/learn/animals/jellyfish/boxjellyfish/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "am_estuarine_crocodile": Source(
        "Australian Museum - Estuarine Crocodile",
        "https://australian.museum/learn/animals/reptiles/estuarine-crocodile/",
        RETRIEVED_DATE,
        "Australia",
        "wildlife",
    ),
    "qld_parks_lamington": Source(
        "Queensland Parks - Lamington visiting safely",
        "https://parks.qld.gov.au/parks/lamington/visiting-safely",
        RETRIEVED_DATE,
        "Queensland / Australia",
        "preparedness",
    ),
    "parks_kakadu_safety": Source(
        "Parks Australia - Kakadu staying safe",
        "https://kakadu.gov.au/plan/plan-your-trip/staying-safe/",
        RETRIEVED_DATE,
        "Northern Territory / Australia",
        "preparedness",
    ),
    "nt_heat": Source(
        "Northern Territory Government - Stay safe in the heat in parks",
        "https://nt.gov.au/parks/safety-rules/beat-the-heat",
        RETRIEVED_DATE,
        "Northern Territory / Australia",
        "preparedness",
    ),
    "bom_thunderstorms": Source(
        "Bureau of Meteorology - Thunderstorms",
        "https://www.bom.gov.au/resources/learn-and-explore/severe-weather-knowledge-centre/thunderstorms",
        RETRIEVED_DATE,
        "Australia",
        "weather",
    ),
    "bom_warnings_alerts": Source(
        "Bureau of Meteorology - Warnings and alerts",
        "https://www.bom.gov.au/weather-and-climate/warnings-and-alerts",
        "2026-06-15",
        "Australia",
        "weather",
    ),
    "bom_floods": Source(
        "Bureau of Meteorology - Floods: what you need to know",
        "https://www.bom.gov.au/news-and-media/floods-what-you-need-to-know",
        "2026-06-15",
        "Australia",
        "weather",
    ),
    "bom_storm_safety": Source(
        "Bureau of Meteorology - Storm safety tips",
        "https://www.bom.gov.au/storm_spotters/handbook/safety_tips.shtml",
        "2026-06-15",
        "Australia",
        "weather",
    ),
    "nsw_plb": Source(
        "NSW National Parks - Personal Locator Beacons and GPS",
        "https://www.nationalparks.nsw.gov.au/safety/bushwalking-safety/personal-locator-beacon",
        RETRIEVED_DATE,
        "NSW / Australia",
        "preparedness",
    ),
    "qld_kutini_safety": Source(
        "Queensland Parks - Kutini-Payamu visiting safely",
        "https://parks.des.qld.gov.au/parks/kutini-payamu/visiting-safely",
        "2026-06-15",
        "Queensland / Australia",
        "preparedness",
    ),
    "nsw_kosciuszko_walk": Source(
        "NSW National Parks - Kosciuszko walk",
        "https://www.nationalparks.nsw.gov.au/things-to-do/walking-tracks/kosciuszko-walk-thredbo-to-mount-kosciuszko",
        "2026-06-15",
        "NSW / Australia",
        "preparedness",
    ),
    "wiki_australia": Source(
        "Wikipedia compressed pack - Australia",
        "https://en.wikipedia.org/wiki/Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_climate": Source(
        "Wikipedia compressed pack - Climate of Australia",
        "https://en.wikipedia.org/wiki/Climate_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_flora": Source(
        "Wikipedia compressed pack - Flora of Australia",
        "https://en.wikipedia.org/wiki/Flora_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_fauna": Source(
        "Wikipedia compressed pack - Fauna of Australia",
        "https://en.wikipedia.org/wiki/Fauna_of_Australia",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
    "wiki_regions": Source(
        "Wikipedia compressed pack - Australian regions",
        "https://en.wikipedia.org/wiki/IBRA",
        RETRIEVED_DATE,
        "Australia",
        "encyclopedia",
    ),
}


KNOWLEDGE_ITEMS: tuple[KnowledgeItem, ...] = (
    KnowledgeItem(
        "snake_bite",
        "Snake bite emergency flow",
        "Treat any suspected snake bite as serious. Call Triple Zero (000). Keep the person still, apply a pressure immobilisation bandage if trained and available, immobilise the limb, and do not wash, cut, suck, or tourniquet the bite. The goal is to slow venom movement and get medical help.",
        SOURCES["healthdirect_snake"],
        ("snake", "bite", "pressure immobilisation", "venom", "first aid"),
        "critical",
    ),
    KnowledgeItem(
        "spider_bite",
        "Spider bite emergency flow",
        "For funnel-web or mouse spider bite, call Triple Zero (000), keep the person still, and use pressure immobilisation. For many other spider bites, clean the area, use a cold pack, and seek medical help if severe symptoms occur. If unsure, choose the more cautious pathway.",
        SOURCES["healthdirect_spider"],
        ("spider", "funnel-web", "mouse spider", "redback", "bite", "first aid"),
        "high",
    ),
    KnowledgeItem(
        "poisoning",
        "Toxin exposure escalation",
        "If someone may have swallowed, inhaled, or touched a toxin, call 13 11 26 for advice. If they are unconscious, not breathing, fitting, collapsing, or severely unwell, call Triple Zero (000) immediately.",
        SOURCES["healthdirect_poisoning"],
        ("poison", "poisoning", "toxin", "ingested", "ate", "13 11 26"),
        "critical",
    ),
    KnowledgeItem(
        "mushrooms",
        "Wild mushroom rule",
        "Do not eat wild mushrooms. Dangerous and deadly mushrooms can look similar to edible species, and photo identification is not safe enough for consumption decisions. If someone has eaten a wild mushroom, call 13 11 26 or Triple Zero (000) if they are seriously unwell.",
        SOURCES["nsw_mushrooms"],
        ("mushroom", "fungus", "fungi", "death cap", "forage", "eat", "bush tucker"),
        "critical",
    ),
    KnowledgeItem(
        "stinging_plants",
        "Stinging plants",
        "Avoid contact with stinging trees and unknown hairy or irritating plants. If stung by a stinging tree, do not rub the area. Healthdirect notes there is no agreed first aid treatment; wax strips may help remove fine hairs. Seek medical care for severe pain or systemic symptoms.",
        SOURCES["healthdirect_stinging_plants"],
        ("stinging tree", "gympie", "plant", "leaf", "hair", "sting"),
        "high",
    ),
    KnowledgeItem(
        "bushwalking_safety",
        "Bushwalking preparation",
        "Before a walk, check conditions, carry water, food, first aid, navigation, warm and wet-weather layers, and tell someone your route and return time. Consider a personal locator beacon for remote areas.",
        SOURCES["nsw_bushwalking"],
        ("checklist", "prepare", "route", "water", "gear", "plb", "beacon"),
        "normal",
    ),
    KnowledgeItem(
        "emergency_orientation",
        "Emergency orientation",
        "If lost or injured, stop, stay calm, conserve battery, stay visible, shelter from exposure, and use exact location information when contacting help. Emergency+ helps communicate GPS coordinates to emergency services when a phone can connect.",
        SOURCES["emergency_plus"],
        ("lost", "navigation", "gps", "000", "112", "emergency", "location"),
        "high",
    ),
    KnowledgeItem(
        "climate_averages",
        "Climate averages, not live forecasts",
        "BoM climate data and climate classification maps are useful for broad seasonal expectations, but they do not replace checking live forecasts, fire danger, flood risk, and park closures before departure.",
        SOURCES["bom_climate_data"],
        ("weather", "climate", "forecast", "temperature", "rain", "bom"),
        "normal",
    ),
    KnowledgeItem(
        "climate_regions",
        "Australian climate regions",
        "Northern tropical areas can bring heat, humidity, monsoon rain, and cyclone-season risks. Southern alpine and tableland areas can change quickly and bring cold exposure. Arid interiors can swing between extreme heat and cold nights. Coastal and temperate areas can still change rapidly.",
        SOURCES["bom_climate_maps"],
        ("tropical", "arid", "alpine", "coastal", "temperate", "desert"),
        "normal",
    ),
    KnowledgeItem(
        "dangerous_animals",
        "Dangerous animals",
        "Australia has venomous snakes and spiders plus other dangerous animals. Do not handle unknown wildlife. Back away calmly, give animals space, and treat bites or severe stings as potentially serious.",
        SOURCES["australian_museum_dangerous"],
        ("dangerous", "animal", "snake", "spider", "wildlife", "venomous"),
        "high",
    ),
    KnowledgeItem(
        "bleeding",
        "Severe bleeding",
        "For severe bleeding, apply firm direct pressure with a clean pad or clothing, keep pressure on, call Triple Zero (000) for major bleeding, and monitor for shock. Do not remove embedded objects; pad around them.",
        SOURCES["healthdirect_poisoning"],
        ("bleeding", "blood", "wound", "cut", "shock"),
        "critical",
    ),
    KnowledgeItem(
        "heat_illness",
        "Heat illness",
        "Heat stress can escalate quickly. Move to shade, rest, cool the person, sip water if conscious, and seek urgent help for confusion, collapse, seizures, hot dry skin, or worsening symptoms.",
        SOURCES["nsw_bushwalking"],
        ("heat", "dehydration", "sun", "hot", "thirst", "heatstroke"),
        "high",
    ),
    KnowledgeItem(
        "hypothermia",
        "Cold exposure",
        "Cold, wind, wet clothing, and fatigue can cause hypothermia even outside alpine areas. Add dry insulation, shelter from wind and rain, share warmth, avoid further heat loss, and seek help for confusion, drowsiness, or severe shivering.",
        SOURCES["nsw_bushwalking"],
        ("cold", "hypothermia", "exposure", "rain", "wind", "shivering"),
        "high",
    ),
    KnowledgeItem(
        "australian_bushland",
        "Australian bushland",
        "Bushland covers many Australian plant communities, from eucalypt woodland and heath to dry sclerophyll forest. For walkers, the practical pattern is shade can be sparse, water can be unreliable, and tracks can look similar after fire, flood, or regrowth.",
        SOURCES["wiki_australia"],
        ("australia", "bushland", "bush", "woodland", "sclerophyll", "track"),
        "normal",
    ),
    KnowledgeItem(
        "eucalypt_forest",
        "Eucalypt forest",
        "Eucalypt forests dominate many walking areas. Bark ribbons, oil-rich leaves, fallen limbs, and open understory are common. In heat, wind, or after storms, be mindful of falling branches, dry fuel, and limited shade on ridges.",
        SOURCES["wiki_flora"],
        ("eucalyptus", "eucalypt", "gum tree", "forest", "woodland", "bark"),
        "normal",
    ),
    KnowledgeItem(
        "acacia_wattle",
        "Acacia and wattle",
        "Acacias, often called wattles, are widespread in Australia. Many have yellow flower heads or spikes and flattened leaf-like phyllodes. Some species have irritant sap or sharp growth, so use observation rather than handling.",
        SOURCES["wiki_flora"],
        ("acacia", "wattle", "yellow flower", "phyllode", "shrub"),
        "normal",
    ),
    KnowledgeItem(
        "banksia",
        "Banksia",
        "Banksias are Australian shrubs and trees with distinctive flower spikes and woody cones. They are useful habitat markers for birds and insects, and often occur in sandy coastal heath, woodland, and dry forest.",
        SOURCES["wiki_flora"],
        ("banksia", "flower spike", "cone", "heath", "coastal", "woodland"),
        "normal",
    ),
    KnowledgeItem(
        "grass_tree",
        "Grass tree",
        "Grass trees have long narrow leaves, a dark trunk or skirt, and tall flower spikes. They grow slowly and can be damaged by trampling; stay on track and avoid breaking flower spikes or leaves.",
        SOURCES["wiki_flora"],
        ("grass tree", "xanthorrhoea", "flower spike", "dry forest", "heath"),
        "normal",
    ),
    KnowledgeItem(
        "spinifex",
        "Spinifex grasslands",
        "Spinifex forms tough hummock grass across arid and semi-arid Australia. It can be sharp, slow to cross, and associated with exposed heat, low water availability, and long distances between shade.",
        SOURCES["wiki_flora"],
        ("spinifex", "hummock grass", "arid", "desert", "exposure"),
        "normal",
    ),
    KnowledgeItem(
        "mangroves",
        "Mangroves",
        "Mangroves grow in tidal coastal zones and estuaries. Walkers should plan around tides, mud, heat, insects, and crocodile country in the north. Boardwalks and marked routes are safer than crossing mudflats.",
        SOURCES["wiki_flora"],
        ("mangrove", "estuary", "tide", "mudflat", "coastal", "crocodile"),
        "high",
    ),
    KnowledgeItem(
        "rainforest",
        "Australian rainforest",
        "Australian rainforests range from tropical north Queensland to temperate gullies in the south. They can bring slippery roots, leeches, low visibility, fast creek rises, and stinging plants near track edges.",
        SOURCES["wiki_regions"],
        ("rainforest", "tropical", "temperate", "leech", "creek", "stinging plant"),
        "normal",
    ),
    KnowledgeItem(
        "alpine_australia",
        "Australian alpine country",
        "Australian alpine and subalpine areas can shift from mild to cold, wet, windy, or whiteout-like conditions quickly. Carry insulation, rain gear, navigation, and a conservative turnaround plan.",
        SOURCES["wiki_regions"],
        ("alpine", "snowy mountains", "high country", "kosciuszko", "cold", "whiteout"),
        "high",
    ),
    KnowledgeItem(
        "blue_mountains",
        "Blue Mountains bushwalking",
        "The Blue Mountains combine sandstone cliffs, eucalyptus forest, steep stairs, waterfalls, and creek gullies. Plan for rapid weather shifts, exposed lookouts, slippery tracks after rain, and cold or windy conditions on ridges.",
        SOURCES["wiki_regions"],
        ("blue mountains", "katoomba", "sandstone", "cliff", "lookout", "waterfall", "bushwalking"),
        "normal",
    ),
    KnowledgeItem(
        "arid_interior",
        "Arid interior",
        "The arid interior has high exposure, long distances, limited water, and large day-night temperature swings. Walkers should plan water, shade, vehicle recovery, satellite communication, and conservative timing around heat.",
        SOURCES["wiki_regions"],
        ("arid", "interior", "desert", "red centre", "water", "heat"),
        "high",
    ),
    KnowledgeItem(
        "tropical_north",
        "Tropical north",
        "Northern Australia has a strong wet-dry seasonal rhythm. Wet-season travel can involve intense rain, flooded crossings, lightning, heat stress, and access closures; dry-season travel still needs heat and water planning.",
        SOURCES["wiki_climate"],
        ("tropical", "north", "wet season", "dry season", "monsoon", "flood"),
        "high",
    ),
    KnowledgeItem(
        "temperate_south",
        "Temperate southern Australia",
        "Southern temperate regions can bring cool changes, fronts, wind, rain, and rapid shifts between sun and cold exposure. Layering, rain protection, and a head torch matter even on short walks.",
        SOURCES["wiki_climate"],
        ("temperate", "southern", "front", "rain", "wind", "cool change"),
        "normal",
    ),
    KnowledgeItem(
        "east_coast_lows",
        "East coast lows",
        "East coast lows can bring damaging wind, heavy rain, rough seas, and fast-changing coastal or range conditions. For bushwalkers this means creek crossings, cliffs, beaches, and exposed ridges deserve extra caution.",
        SOURCES["wiki_climate"],
        ("east coast low", "coast", "heavy rain", "wind", "creek", "ridge"),
        "high",
    ),
    KnowledgeItem(
        "southerly_buster",
        "Southerly buster",
        "A southerly buster is a strong cool southerly change that can affect parts of southeast Australia, especially coastal New South Wales. It may bring abrupt wind, temperature drop, and rough coastal conditions.",
        SOURCES["wiki_climate"],
        ("southerly buster", "cool change", "wind", "coast", "nsw"),
        "normal",
    ),
    KnowledgeItem(
        "cumulonimbus",
        "Cumulonimbus cloud",
        "Tall cauliflower-like cloud with dark bases or an anvil top can indicate thunderstorm development. Treat cloud reading as an observation, not a forecast, and avoid exposed ridges, lone trees, and creek beds as storms build.",
        SOURCES["wiki_climate"],
        ("cloud", "cumulonimbus", "anvil", "storm", "lightning", "weather"),
        "high",
    ),
    KnowledgeItem(
        "kangaroo_wallaby",
        "Kangaroos and wallabies",
        "Kangaroos and wallabies are common macropods. Give them space, especially large males and animals near roads or campsites. Avoid feeding wildlife, which can make animals bolder and less healthy.",
        SOURCES["wiki_fauna"],
        ("kangaroo", "wallaby", "macropod", "wildlife", "camp"),
        "normal",
    ),
    KnowledgeItem(
        "wombat",
        "Wombat",
        "Wombats are sturdy burrowing marsupials. Burrows can undermine ground near tracks and camps. Give animals space, avoid blocking burrow entrances, and watch footing around holes in low light.",
        SOURCES["wiki_fauna"],
        ("wombat", "burrow", "marsupial", "track", "hole"),
        "normal",
    ),
    KnowledgeItem(
        "koala",
        "Koala",
        "Koalas live in eucalypt habitats and may be high in trees or moving on the ground between trees. Keep distance, keep dogs away, and report injured animals to local wildlife rescue where possible.",
        SOURCES["wiki_fauna"],
        ("koala", "eucalypt", "wildlife", "rescue", "tree"),
        "normal",
    ),
    KnowledgeItem(
        "echidna",
        "Echidna",
        "Echidnas are monotremes with spines and a long snout. If encountered, give space and avoid disturbing them; they may dig in or curl up when stressed.",
        SOURCES["wiki_fauna"],
        ("echidna", "monotreme", "spines", "snout", "wildlife"),
        "normal",
    ),
    KnowledgeItem(
        "platypus",
        "Platypus",
        "Platypus live around freshwater creeks and rivers. Sightings are easiest at quiet dawn or dusk. Do not disturb banks or burrows; males have venomous spurs, so never handle one.",
        SOURCES["wiki_fauna"],
        ("platypus", "creek", "river", "freshwater", "spur", "venom"),
        "normal",
    ),
    KnowledgeItem(
        "dingo",
        "Dingo",
        "Dingoes are wild canids found in many regions. Keep food secured, do not feed them, supervise children, and follow local park guidance. Back away calmly if one approaches.",
        SOURCES["wiki_fauna"],
        ("dingo", "wild dog", "canid", "camp", "food", "fraser island", "kgari"),
        "high",
    ),
    KnowledgeItem(
        "cassowary",
        "Cassowary",
        "Cassowaries inhabit parts of tropical north Queensland. They are large, powerful birds. Do not feed or approach them; give a clear escape path and back away calmly.",
        SOURCES["wiki_fauna"],
        ("cassowary", "tropical", "queensland", "bird", "rainforest"),
        "high",
    ),
    KnowledgeItem(
        "crocodile_country",
        "Crocodile country",
        "Saltwater crocodiles occur across northern Australia in coastal, river, wetland, and sometimes inland floodplain habitats. Stay back from water edges and follow local signs and ranger advice.",
        SOURCES["wiki_fauna"],
        ("crocodile", "saltwater crocodile", "north", "river", "wetland", "estuary"),
        "critical",
    ),
    KnowledgeItem(
        "ticks_leeches",
        "Ticks and leeches",
        "Ticks and leeches are common in some humid bushland and rainforest areas. Wear protective clothing, check skin after walks, remove ticks carefully, and monitor for allergic reactions or illness.",
        SOURCES["wiki_fauna"],
        ("tick", "leech", "rainforest", "bite", "allergy", "skin"),
        "normal",
    ),
    KnowledgeItem(
        "bull_ant",
        "Bull ants",
        "Bull ants are large Australian ants with painful stings and strong vision. Avoid nests and do not stand on mound areas. People with severe allergic reactions need urgent medical care.",
        SOURCES["wiki_fauna"],
        ("bull ant", "ant", "sting", "nest", "allergy"),
        "high",
    ),
    KnowledgeItem(
        "blue_bottle",
        "Bluebottle",
        "Bluebottles can wash onto Australian beaches and cause painful stings. Avoid touching stranded tentacles and check local beach advice before swimming or coastal walking.",
        SOURCES["wiki_fauna"],
        ("bluebottle", "beach", "sting", "tentacle", "coast"),
        "normal",
    ),
    KnowledgeItem(
        "box_jellyfish_irukandji_first_aid",
        "Box jellyfish",
        "Box jellyfish and Irukandji risk is concentrated in northern tropical waters, especially warmer months. Use stinger-resistant swimwear, obey local signs, and avoid swimming where stinger risk is posted.",
        SOURCES["wiki_fauna"],
        ("box jellyfish", "irukandji", "stinger", "tropical", "beach", "north"),
        "critical",
    ),
    KnowledgeItem(
        "blue_ringed_octopus",
        "Blue-ringed octopus",
        "Blue-ringed octopuses can occur in tide pools and shallow coastal waters. They are small, shy, and highly venomous; the practical rule is never handle shells, rocks, or marine animals from rock pools.",
        SOURCES["am_blue_ringed_octopus"],
        ("blue-ringed octopus", "blue lined octopus", "tide pool", "rock pool", "marine", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "stonefish",
        "Stonefish",
        "Stonefish are extremely well-camouflaged venomous fish in northern coastal and reef environments. Wear protective footwear in suitable habitat and avoid placing hands or feet where you cannot see.",
        SOURCES["am_stonefish"],
        ("stonefish", "reef stonefish", "reef", "coast", "venom", "footwear"),
        "critical",
    ),
    KnowledgeItem(
        "yellow_bellied_sea_snake",
        "Yellow-bellied sea snake",
        "Yellow-bellied sea snakes are highly venomous sea snakes that may occasionally appear near beaches, mangroves, or inter-tidal areas. Do not handle a stranded or swimming sea snake; keep people and dogs back and use the snake bite flow for any suspected bite.",
        SOURCES["am_yellow_bellied_sea_snake"],
        ("yellow-bellied sea snake", "yellow bellied sea snake", "sea snake", "pelagic snake", "beach snake", "snake bite"),
        "critical",
    ),
    KnowledgeItem(
        "red_bellied_black_snake",
        "Red-bellied black snake",
        "Red-bellied black snakes often occur near swamps, creeks, ponds, and damp eastern Australian habitats. Their colouring can be distinctive, but do not approach for identification; give space and treat any suspected bite as an emergency.",
        SOURCES["am_red_bellied_black_snake"],
        ("red-bellied black snake", "red belly black snake", "red bellied black snake", "black snake", "creek snake", "snake bite"),
        "critical",
    ),
    KnowledgeItem(
        "brown_snake",
        "Eastern brown snake",
        "Eastern brown snakes are widespread in eastern Australia and can vary from light tan to dark brown. Do not approach or attempt to identify closely. Stand still or back away slowly and leave an escape path.",
        SOURCES["am_eastern_brown_snake"],
        ("eastern brown snake", "brown snake", "snake", "venom", "grassland"),
        "critical",
    ),
    KnowledgeItem(
        "western_brown_snake",
        "Western brown snake",
        "Western brown snakes have potent venom and a bite from any brown snake should be treated as life-threatening. They can be variable in colour, so field safety should focus on distance and first aid rather than species certainty.",
        SOURCES["am_western_brown_snake"],
        ("western brown snake", "gwardar", "brown snake", "snake", "venom", "life-threatening"),
        "critical",
    ),
    KnowledgeItem(
        "tiger_snake",
        "Tiger snake",
        "Tiger snakes occur in southern Australia and often around wetlands, creeks, or damp habitats. Keep distance from snakes and use the snake bite flow for any suspected bite.",
        SOURCES["am_tiger_snake"],
        ("tiger snake", "snake", "wetland", "creek", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "taipan",
        "Taipan",
        "Taipans are highly venomous Australian snakes, including coastal and inland species. Most walkers should never try to distinguish species in the field; distance and first-aid response matter more.",
        SOURCES["am_coastal_taipan"],
        ("taipan", "snake", "coastal taipan", "inland taipan", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "inland_taipan",
        "Inland taipan",
        "Inland taipans are often cited for extremely potent venom but are rarely encountered by typical bushwalkers. If any taipan-like snake is suspected, do not pursue identification; keep distance and treat bites as a snake-bite emergency.",
        SOURCES["am_inland_taipan"],
        ("inland taipan", "fierce snake", "taipan", "snake", "venom"),
        "critical",
    ),
    KnowledgeItem(
        "redback_spider",
        "Redback spider",
        "Redback spiders are found Australia-wide and are common around dry sheltered places, toilets, sheds, gear, and campsites. Shake out gear, use gloves around stored items, wash bites, use a cold pack, and seek advice for severe or persistent pain.",
        SOURCES["am_redback_spider"],
        ("redback", "spider", "camp", "toilet", "gear", "bite"),
        "high",
    ),
    KnowledgeItem(
        "redback_first_aid",
        "Redback spider first aid",
        "For a likely redback bite, wash the area, use a cold pack for pain and swelling, and call 13 11 26 or seek medical care if pain is severe, persistent, or symptoms spread. Do not use pressure immobilisation for redback bites.",
        SOURCES["qld_poisons_spider"],
        ("redback bite", "red back bite", "latrodectus", "spider bite", "cold pack", "do not pressure immobilisation"),
        "high",
    ),
    KnowledgeItem(
        "funnel_web_spider",
        "Funnel-web spider",
        "Funnel-web spiders occur in parts of eastern Australia and can shelter in damp ground, burrows, shoes, or gear. Avoid handling spiders and use the pressure immobilisation pathway for suspected funnel-web or mouse spider bites.",
        SOURCES["am_sydney_funnel_web"],
        ("funnel-web", "funnel web", "sydney funnel-web", "spider", "burrow", "shoe", "gear", "bite"),
        "critical",
    ),
    KnowledgeItem(
        "box_jellyfish",
        "Box jellyfish and Irukandji",
        "Box jellyfish and Irukandji risks are concentrated in northern tropical waters and warmer months. Use local signs and stinger-safe areas. For suspected major box jellyfish sting, call 000, remove from water if safe, rinse tentacles with seawater, and use vinegar where recommended for box jellyfish/Irukandji.",
        SOURCES["healthdirect_jellyfish"],
        ("box jellyfish", "irukandji", "marine stinger", "vinegar", "tentacles", "tropical water"),
        "critical",
    ),
    KnowledgeItem(
        "sea_creature_first_aid",
        "Sea creature bites and stings",
        "For blue-ringed octopus, cone shell, stonefish, or severe marine stings, get urgent medical help. Keep the person still, avoid further contact, and follow local first-aid advice; stonefish pain may need hot-water first aid where safe and supervised.",
        SOURCES["qld_poisons_sea_creatures"],
        ("blue-ringed octopus", "cone shell", "stonefish sting", "sea creature", "marine bite", "hot water"),
        "critical",
    ),
    KnowledgeItem(
        "estuarine_crocodile",
        "Estuarine crocodile country",
        "Estuarine or saltwater crocodiles occur in northern coastal areas, rivers, estuaries, creeks, swamps, lagoons, and billabongs. Obey signs, keep back from water edges, never clean fish or camp near the edge, and do not assume clear shallow water is safe.",
        SOURCES["am_estuarine_crocodile"],
        ("estuarine crocodile", "saltwater crocodile", "crocodile", "croc country", "water edge", "billabong"),
        "critical",
    ),
    KnowledgeItem(
        "rainforest_stinging_tree",
        "Rainforest stinging tree and track hazards",
        "In subtropical and tropical rainforest, stay on track, watch for slippery roots, leeches, ticks, creek rises, and giant stinging trees with large heart-shaped leaves. Do not touch stinging tree leaves, including dead leaves.",
        SOURCES["qld_parks_lamington"],
        ("rainforest", "stinging tree", "gympie gympie", "heart-shaped leaves", "leech", "tick", "slippery roots"),
        "high",
    ),
    KnowledgeItem(
        "remote_heat_water",
        "Remote heat and water planning",
        "In the Red Centre, Top End, and exposed inland parks, heat illness can build quickly. Start hydrated, carry more water than a short city walk would suggest, avoid extreme heat, rest in shade if unwell, and turn around before the group is depleted.",
        SOURCES["nt_heat"],
        ("heat", "red centre", "top end", "water", "hydration", "shade", "remote"),
        "high",
    ),
    KnowledgeItem(
        "kakadu_wet_season",
        "Kakadu and tropical wet-season safety",
        "Tropical parks can combine heat stress, storms, flooded crossings, crocodile risk, and seasonal access closures. Read local signs, check closures before leaving service, and do not enter closed or flooded areas.",
        SOURCES["parks_kakadu_safety"],
        ("kakadu", "wet season", "flooded crossing", "crocodile", "heat stress", "closure"),
        "high",
    ),
    KnowledgeItem(
        "thunderstorm_lightning",
        "Thunderstorm and lightning field signs",
        "Thunderstorms can bring lightning, damaging wind, hail, intense rain, and flash flooding. If tall dark clouds, thunder, or fast-building storms appear, leave exposed ridges, cliffs, beaches, lone trees, and creek beds early.",
        SOURCES["bom_thunderstorms"],
        ("thunderstorm", "lightning", "hail", "flash flood", "anvil", "dark cloud", "ridge", "creek bed"),
        "high",
    ),
    KnowledgeItem(
        "plb_trip_intentions",
        "PLB and trip intentions",
        "For remote routes, carry a registered PLB or satellite communicator, tell someone your route and return time, and know when they should raise the alarm. A PLB is a last-resort emergency beacon when phone coverage is absent or unreliable.",
        SOURCES["nsw_plb"],
        ("plb", "personal locator beacon", "satellite communicator", "trip intention", "no reception", "raise the alarm"),
        "high",
    ),
    KnowledgeItem(
        "bush_tucker_context",
        "Bush tucker context",
        "Bush tucker knowledge is local, seasonal, and culturally grounded. Treat general app notes as education only. Do not consume wild foods without expert local identification and permission to harvest.",
        SOURCES["wiki_flora"],
        ("bush tucker", "foraging", "edible", "food", "indigenous knowledge", "seasonal"),
        "high",
    ),
    KnowledgeItem(
        "track_navigation",
        "Track navigation in Australian bush",
        "Australian tracks can become unclear after fire, flood, leaf fall, or animal pads. Use map, compass or GPS, turn back early when uncertain, and avoid splitting the group.",
        SOURCES["wiki_australia"],
        ("navigation", "track", "map", "gps", "lost", "bushwalking"),
        "normal",
    ),
    KnowledgeItem(
        "water_crossings",
        "Creek and river crossings",
        "Creeks can rise quickly after upstream rain, especially in gorges, tropics, and steep catchments. If a crossing looks fast, deep, cloudy, or rising, wait or turn back.",
        SOURCES["wiki_regions"],
        ("creek", "river", "crossing", "flood", "gorge", "rain"),
        "high",
    ),
    KnowledgeItem(
        "fire_weather_context",
        "Fire weather context",
        "Hot, dry, windy weather can make bushfire behaviour more dangerous. Offline notes cannot know current fire danger, so check official fire services before leaving service and avoid remote routes on severe days.",
        SOURCES["wiki_climate"],
        ("fire", "bushfire", "wind", "heat", "dry", "fire danger"),
        "high",
    ),
    KnowledgeItem(
        "trip_intentions_overdue_plan",
        "Trip intentions and overdue plan",
        "For remote, extreme-weather, overnight, alpine, or off-track walks, leave a trip intention with route, party, vehicle, emergency devices, finish time, and a clear overdue trigger. Your emergency contact must know when and how to contact police if you do not return.",
        SOURCES["nsw_trip_intentions"],
        ("trip intention", "overdue", "emergency contact", "route plan", "remote walk", "search rescue"),
        "high",
    ),
    KnowledgeItem(
        "lost_stop_signal_shelter",
        "Lost or misplaced track flow",
        "If the track is lost, stop early, keep the group together, mark your last known point, check map and GPS calmly, and avoid pushing deeper into uncertain terrain. If you cannot confidently relocate the route, shelter, stay visible, conserve battery, and prepare to signal for help.",
        SOURCES["emergency_plus"],
        ("lost", "misplaced track", "track lost", "last known point", "shelter", "signal", "battery"),
        "high",
    ),
    KnowledgeItem(
        "no_reception_plb_comms",
        "No reception communications",
        "Many walking areas have patchy or no mobile reception. Before leaving service, cache maps and weather, share the route, and carry a PLB or satellite communicator for remote routes. A phone is still useful for GPS and Emergency+ coordinates when a signal becomes available.",
        SOURCES["nsw_plb"],
        ("no reception", "mobile coverage", "plb", "satellite communicator", "offline maps", "emergency plus"),
        "high",
    ),
    KnowledgeItem(
        "floodwater_turnback",
        "Floodwater and creek turnback",
        "Floods and flash flooding can be life-threatening. Do not walk, ride, or drive through floodwater. If a creek or causeway is fast, cloudy, rising, above stepping stones, or rain is falling upstream, wait on safe ground or turn back.",
        SOURCES["bom_floods"],
        ("floodwater", "flash flood", "creek crossing", "river crossing", "causeway", "turn back"),
        "critical",
    ),
    KnowledgeItem(
        "lightning_exposure_shelter",
        "Lightning and exposed-ground shelter",
        "All thunderstorms produce lightning. If thunder, building cumulonimbus, or lightning appears, leave ridges, summits, cliff edges, beaches, lone trees, water, and metal fences early. Seek substantial shelter where possible and avoid becoming the highest point.",
        SOURCES["bom_storm_safety"],
        ("lightning", "thunder", "ridge", "summit", "beach", "lone tree", "storm shelter"),
        "high",
    ),
    KnowledgeItem(
        "warnings_before_offline",
        "Warnings before heading offline",
        "Before a trip, check official warnings and alerts for severe weather, bushwalker weather alerts, flood watches, fire danger, park closures, and road access. Offline weather packs are planning aids, not warnings.",
        SOURCES["bom_warnings_alerts"],
        ("warnings", "alerts", "bushwalkers weather alert", "park closures", "fire danger", "road access"),
        "high",
    ),
    KnowledgeItem(
        "kosciuszko_alpine_conditions",
        "Kosciuszko alpine conditions",
        "Kosciuszko and the Snowy Mountains can bring cold, wind, snow, low cloud, UV, and sudden weather changes even outside deep winter. Carry warm and waterproof layers, navigation, and a conservative turnaround time.",
        SOURCES["nsw_kosciuszko_walk"],
        ("kosciuszko", "kosciusko", "snowy mountains", "alpine", "thredbo", "cold", "low cloud"),
        "high",
    ),
    KnowledgeItem(
        "rainforest_creek_tree_hazards",
        "Rainforest creek and stinging-tree hazards",
        "Rainforest tracks can combine slippery roots, leeches, creek rises, low visibility, and stinging trees. Avoid touching large hairy or heart-shaped leaves, treat creek rises as a turnback signal, and keep spare dry layers for stops.",
        SOURCES["qld_kutini_safety"],
        ("rainforest", "creek rise", "stinging tree", "gympie", "slippery roots", "leeches"),
        "high",
    ),
    KnowledgeItem(
        "coastal_rockpool_marine_hazards",
        "Coastal rockpool and marine hazards",
        "On beaches and rocky shores, watch tides, swell, slippery rock, bluebottles, marine stingers, stonefish, cone shells, and blue-ringed octopus. Do not handle shells or animals, and keep dogs and children back from stranded sea snakes or unknown marine life.",
        SOURCES["qld_kutini_safety"],
        ("coast", "rockpool", "tide", "swell", "blue-ringed octopus", "stonefish", "sea snake"),
        "high",
    ),
    KnowledgeItem(
        "group_turnaround_decision",
        "Group turnaround decision",
        "Set a turnaround time before starting. Turn around when the slowest person is tiring, water is running low, weather is building, navigation is uncertain, or daylight is closing. Staying together is usually safer than sending one person ahead.",
        SOURCES["nsw_bushwalking"],
        ("turnaround time", "slowest person", "group", "daylight", "water low", "navigation uncertain"),
        "high",
    ),
)


DANGER_CARDS = (
    {
        "title": "Snakes",
        "severity": "critical",
        "signals": "Any suspected bite, unexplained collapse, bite marks, or seeing a snake nearby.",
        "actions": [
            "Call Triple Zero (000).",
            "Keep the person still and calm.",
            "Use pressure immobilisation if trained and available.",
            "Do not wash, cut, suck, or tourniquet the bite.",
        ],
        "source": SOURCES["healthdirect_snake"],
    },
    {
        "title": "Funnel-web or mouse spider",
        "severity": "critical",
        "signals": "Large dark spider, severe pain, sweating, tingling, nausea, breathing trouble, or uncertainty.",
        "actions": [
            "Call Triple Zero (000).",
            "Keep still.",
            "Use pressure immobilisation for suspected funnel-web or mouse spider bite.",
        ],
        "source": SOURCES["healthdirect_spider"],
    },
    {
        "title": "Redback spider",
        "severity": "high",
        "signals": "Small dark spider, red/orange stripe, dry sheltered web, persistent local pain, sweating, nausea, or spreading symptoms.",
        "actions": [
            "Wash the bite area.",
            "Use a cold pack for pain and swelling.",
            "Call 13 11 26 or seek medical help for severe or persistent pain.",
            "Do not use pressure immobilisation for a likely redback bite.",
        ],
        "source": SOURCES["qld_poisons_spider"],
    },
    {
        "title": "Wild mushrooms",
        "severity": "critical",
        "signals": "Any wild mushroom or unknown fungus, even if it looks familiar.",
        "actions": [
            "Do not eat wild mushrooms.",
            "Do not rely on a photo to decide if a mushroom is edible.",
            "If eaten, call 13 11 26 or 000 if seriously unwell.",
        ],
        "source": SOURCES["nsw_mushrooms"],
    },
    {
        "title": "Marine stingers and venomous sea creatures",
        "severity": "critical",
        "signals": "Tropical jellyfish sting, blue-ringed octopus, stonefish, cone shell, severe pain, collapse, breathing difficulty, or uncertainty.",
        "actions": [
            "Call Triple Zero (000) for severe symptoms or major tropical jellyfish stings.",
            "Get out of the water if safe.",
            "Use local beach signs and lifesaver instructions for vinegar, seawater, hot water, or cold packs.",
            "Never handle shells, octopus, stranded sea snakes, or camouflaged reef animals.",
        ],
        "source": SOURCES["qld_poisons_sea_creatures"],
    },
    {
        "title": "Crocodile country",
        "severity": "critical",
        "signals": "Northern rivers, estuaries, billabongs, mangroves, tidal crossings, or crocodile warning signs.",
        "actions": [
            "Obey signs and ranger advice.",
            "Keep well back from water edges.",
            "Do not swim, wade, clean fish, or camp near the edge where crocodiles may occur.",
        ],
        "source": SOURCES["am_estuarine_crocodile"],
    },
    {
        "title": "Stinging trees and irritating plants",
        "severity": "high",
        "signals": "Hairy leaves/stems, rainforest tracks, sudden intense sting, embedded fine hairs.",
        "actions": [
            "Do not rub the area.",
            "Avoid touching unknown hairy plants.",
            "Seek medical care for severe pain or systemic symptoms.",
        ],
        "source": SOURCES["healthdirect_stinging_plants"],
    },
    {
        "title": "Heat, dehydration, and exposure",
        "severity": "high",
        "signals": "Confusion, collapse, severe thirst, no sweating, shivering, drowsiness, worsening fatigue.",
        "actions": [
            "Stop and shelter from the hazard.",
            "Cool or warm the person as appropriate.",
            "Escalate early if symptoms are severe or worsening.",
        ],
        "source": SOURCES["nsw_bushwalking"],
    },
)


CHECKLIST_SECTIONS = (
    {
        "title": "Tell someone",
        "items": [
            "Route, party names, vehicle details, planned return time, and escalation time.",
            "Emergency contact understands when to raise the alarm.",
        ],
    },
    {
        "title": "Navigation and communication",
        "items": [
            "Offline map or paper map and compass.",
            "Phone charged, power bank packed, location services enabled.",
            "PLB or satellite communicator for remote routes.",
            "Trip intention and escalation time left with a reliable contact.",
            "Emergency+ installed and tested before losing service.",
        ],
    },
    {
        "title": "Water, food, and weather",
        "items": [
            "Enough water plus backup treatment plan.",
            "Food plus emergency extra.",
            "Live BoM forecast, fire danger, park status, and flood/track conditions checked before departure.",
            "Heat plan for inland or tropical walks: early start, shade stops, and turnaround time.",
        ],
    },
    {
        "title": "First aid and exposure",
        "items": [
            "First aid kit with snake bandage, wound dressings, blister care, and any personal medicines.",
            "Sun protection, rain shell, warm layer, and head torch.",
            "Coastal or northern route hazards checked: marine stingers, tides, crocodile signs, and footwear for reef or rock pools.",
            "Rainforest hazards checked: stinging trees, leeches, ticks, slippery roots, and creek rises.",
            "Know the limits: Outbush AI is a field aid, not emergency services or medical care.",
        ],
    },
)


from .expanded_content import build_expanded_knowledge


EXPANDED_KNOWLEDGE_ITEMS = build_expanded_knowledge(Source, KnowledgeItem, RETRIEVED_DATE)
KNOWLEDGE_ITEMS = (*KNOWLEDGE_ITEMS, *EXPANDED_KNOWLEDGE_ITEMS)
